FROM node:18 AS build

WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli
COPY ./client/package*.json ./

RUN npm install

COPY ./client .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/client/browser /usr/share/nginx/html
COPY ./client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]