services:
  client:
    image: client
    container_name: client
    build:
      context: .
      dockerfile: ./client/dockerfile
    networks:
      - innernetwork
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - server
    restart: always

  server:
    image: server
    container_name: server
    build:
      context: .
      dockerfile: ./server/dockerfile
    networks:
      - innernetwork
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - db
    restart: always

  db:
    container_name: postgres
    image: postgres
    networks:
      - innernetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data-1:/var/lib/postgresql/data
    restart: always
volumes:
  data-1:
    driver: local
    driver_opts:
      type: none
      device: ${POSTGRES_VOLUME_PATH}
      o: bind
networks:
  innernetwork:
    driver: bridge
