# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./server .

# Build the NestJS application
RUN npm run build

# Copy the entrypoint script
COPY ./server/entrypoint.sh ./entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x ./entrypoint.sh

# Expose the application port
EXPOSE 3000

# Use the entrypoint script to start the application
CMD ["/app/entrypoint.sh"]